### ISSUE TITLE
Odd exception

### ISSUE THREAD

**Issue by derekantrican** [derekantrican/YouTubeSubscriptionDownloader#17]
Getting an odd exception (null reference). Need to track it down. Here is the stack trace:

at YouTubeSubscriptionDownloader.Form1.CheckForNewVideoFromSubscriptions(CancellationToken token) in C:\Users\derek.antrican\source\repos\YouTubeSubscriptionDownloader\YouTubeSubscriptionDownloader\Form1.cs:line 501
   at YouTubeSubscriptionDownloader.Form1.<Timer_Tick>b__19_0() in C:\Users\derek.antrican\source\repos\YouTubeSubscriptionDownloader\YouTubeSubscriptionDownloader\Form1.cs:line 303
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

**Comment by derekantrican** [comment]
I'm going to assume this is resolved
